### ISSUE TITLE
Program crashes when .reuse/dep5 is not valid

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#2]
```
$ reuse lint
SUMMARY

Bad licenses: 0
Missing licenses: 0
Unused licenses: 0
Used licenses: CC0-1.0, GPL-3.0-or-later
Read errors: 0
Files with copyright information: 6 / 6
Files with license information: 6 / 6

Congratulations! Your project is REUSE compliant :-)
reuse.project - ERROR - .reuse/dep5 has syntax errors
Traceback (most recent call last):
  File "/home/carmen/Projektoj/reuse/src/reuse/project.py", line 256, in _copyright
    self._copyright_val = Copyright(fp)
  File "/home/carmen/.virtualenvs/reuse/lib64/python3.7/site-packages/debian/copyright.py", line 150, in __init__
    raise NotMachineReadableError('no paragraphs in input')
debian.copyright.NotMachineReadableError: no paragraphs in input
```

**Comment by alandtse** [comment]
Another related error is if you do not include a Copyright field.
```python
Traceback (most recent call last):
  File "/Users/at1000183352/Library/Python/3.7/bin/reuse", line 10, in <module>
    sys.exit(main())
  File "/Users/at1000183352/Library/Python/3.7/lib/python/site-packages/reuse/_main.py", line 225, in main
    return parsed_args.func(parsed_args, out)
  File "/Users/at1000183352/Library/Python/3.7/lib/python/site-packages/reuse/lint.py", line 260, in run
    report = ProjectReport.generate(project, paths)
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
  File "/Users/at1000183352/Library/Python/3.7/lib/python/site-packages/reuse/report.py", line 161, in generate
    lint_file_info = FileReport.generate(project, file_)
  File "/Users/at1000183352/Library/Python/3.7/lib/python/site-packages/reuse/report.py", line 300, in generate
    spdx_info = project.spdx_info_of(path)
  File "/Users/at1000183352/Library/Python/3.7/lib/python/site-packages/reuse/project.py", line 119, in spdx_info_of
    if self._copyright:
  File "/Users/at1000183352/Library/Python/3.7/lib/python/site-packages/reuse/project.py", line 219, in _copyright
    self._copyright_val = Copyright(fp)
  File "/Users/at1000183352/Library/Python/3.7/lib/python/site-packages/debian/copyright.py", line 155, in __init__
    pf = FilesParagraph(p, strict)
  File "/Users/at1000183352/Library/Python/3.7/lib/python/site-packages/debian/copyright.py", line 510, in __init__
    _complain('Files paragraph missing Copyright field', strict)
  File "/Users/at1000183352/Library/Python/3.7/lib/python/site-packages/debian/copyright.py", line 84, in _complain
#!/usr/bin/python
    raise MachineReadableFormatError(msg)
debian.copyright.MachineReadableFormatError: Files paragraph missing Copyright field
```

This can probably just be handled by a simple try except block.

**Comment by carmenbianca** [comment]
Duplicate of #107
