### ISSUE TITLE
Error error message when unusual files are found in LICENSES/

### ISSUE THREAD

**Issue by lucaslasota** [fsfe/reuse-tool#239]
Hi,
the reuse linter tool in the repository https://gitlab.com/arpa2/steamworks  gives the following output:

`reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/LICENSE.SteamWorks, resolving to LICENSE. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/LICENSE.fcgi, resolving to LICENSE. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - CRITICAL - LICENSE is the SPDX License Identifier of both LICENSES/LICENSE.fcgi and LICENSES/LICENSE.SteamWorks
Traceback (most recent call last):
  File "/home/Hacker2018/.local/bin/reuse", line 11, in <module>
    sys.exit(main())
  File "/home/Hacker2018/.local/lib/python3.6/site-packages/reuse/_main.py", line 225, in main
    return parsed_args.func(parsed_args, out)
  File "/home/Hacker2018/.local/lib/python3.6/site-packages/reuse/lint.py", line 255, in run
    project = create_project()
  File "/home/Hacker2018/.local/lib/python3.6/site-packages/reuse/project.py", line 297, in create_project
    return Project(root)
  File "/home/Hacker2018/.local/lib/python3.6/site-packages/reuse/project.py", line 63, in __init__
    self.licenses = self._licenses()
  File "/home/Hacker2018/.local/lib/python3.6/site-packages/reuse/project.py", line 277, in _licenses
    "Multiple licenses resolve to {}".format(identifier)
RuntimeError: Multiple licenses resolve to LICENSE`

The project has a top-level LICENSE file, and LICENSES/ for that and license texts from bundled software.  

Please give it a look.

Thanks a lot

**Comment by mxmehl** [comment]
The linter does not expect these files, and I wonder what they are doing there. I would suggest to rename them to the `LicenseRef-xyz.txt` format, and use this string then.

Also see the spec for this: https://reuse.software/spec/#license-files

Since I don't really see a tool issue here, I'll close. But feel free to reopen if you think it's a bug :)
