### ISSUE TITLE
ModuleNotFoundError: No module named 'boolean.boolean'

### ISSUE THREAD

**Issue by miffels** [fsfe/reuse-tool#260]
Hi,

I just installed the tool `0.11.1` on my Mac and can't seem to use it - not sure what's wrong. I used the installation from pip3 path as pointed out in the README:

```bash
% sw_vers -productVersion
10.15.6
% python --version
Python 3.7.7
% pip3 install --user reuse
Requirement already satisfied: reuse in /Users/.../Library/Python/3.7/lib/python/site-packages (0.11.1)
Requirement already satisfied: requests in /Users/.../Library/Python/3.7/lib/python/site-packages (from reuse) (2.24.0)
Requirement already satisfied: license-expression in /Users/.../Library/Python/3.7/lib/python/site-packages (from reuse) (1.2)
Requirement already satisfied: python-debian in /Users/.../Library/Python/3.7/lib/python/site-packages (from reuse) (0.1.37)
Requirement already satisfied: boolean.py in /usr/local/lib/python3.7/site-packages (from reuse) (3.7)
Requirement already satisfied: binaryornot in /Users/.../Library/Python/3.7/lib/python/site-packages (from reuse) (0.4.4)
Requirement already satisfied: Jinja2 in /Users/.../Library/Python/3.7/lib/python/site-packages (from reuse) (2.10.1)
Requirement already satisfied: idna<3,>=2.5 in /Users/.../Library/Python/3.7/lib/python/site-packages (from requests->reuse) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/.../Library/Python/3.7/lib/python/site-packages (from requests->reuse) (1.25.10)
Requirement already satisfied: certifi>=2017.4.17 in /Users/.../Library/Python/3.7/lib/python/site-packages (from requests->reuse) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/.../Library/Python/3.7/lib/python/site-packages (from requests->reuse) (3.0.4)
Requirement already satisfied: six in /Users/.../Library/Python/3.7/lib/python/site-packages (from python-debian->reuse) (1.12.0)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/.../Library/Python/3.7/lib/python/site-packages (from Jinja2->reuse) (1.1.1)
% reuse init
Traceback (most recent call last):
  File "/Users/.../Library/Python/3.7/bin/reuse", line 5, in <module>
    from reuse._main import main
  File "/Users/.../Library/Python/3.7/lib/python/site-packages/reuse/__init__.py", line 13, in <module>
    from boolean.boolean import Expression
ModuleNotFoundError: No module named 'boolean.boolean'
```

It does look like the dependency was resolved. Any ideas?

Thanks,
Michael

**Comment by mxmehl** [comment]
I cannot reproduce this on my Arch Linux machine. Any Mac user here who could test this?

**Comment by miffels** [comment]
[I've been able to work around this by means of `virtualenv`.](https://github.com/SAP-samples/cloud-mobile-services-continuous-integration/commit/abff81e22a9c4ae11cd1357fef108b755a0717aa)
