### ISSUE TITLE
ModuleNotFoundError: No module named 'pwd' on Windows

### ISSUE THREAD

**Issue by schlauch** [fsfe/reuse-tool#322]
## Steps to reproduce

- Install latest resue version `pip install reuse`
- Run reuse: `reuse --version`
- The following error comes up:
```
$ reuse --version
Traceback (most recent call last):
  File "c:\programdata\miniforge3\envs\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\miniforge3\envs\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniforge3\envs\python\Scripts\reuse.exe\__main__.py", line 4, in <module>
  File "c:\programdata\miniforge3\envs\python\lib\site-packages\reuse\_main.py", line 14, in <module>
    from . import (
  File "c:\programdata\miniforge3\envs\python\lib\site-packages\reuse\download.py", line 17, in <module>
    from ._util import (
  File "c:\programdata\miniforge3\envs\python\lib\site-packages\reuse\_util.py", line 26, in <module>
    from debian.copyright import Copyright
  File "c:\programdata\miniforge3\envs\python\lib\site-packages\debian\copyright.py", line 59, in <module>
    from debian import deb822
  File "c:\programdata\miniforge3\envs\python\lib\site-packages\debian\deb822.py", line 321, in <module>
    import debian.changelog
  File "c:\programdata\miniforge3\envs\python\lib\site-packages\debian\changelog.py", line 93, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'
```

### Environment
- Operating system: Windows 10
- Python 3.8.8 (install via conda)
- Installed dependencies through pip

```
Collecting reuse
  Using cached reuse-0.12.1-py3-none-any.whl (135 kB)
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting python-debian
  Using cached python_debian-0.1.39-py3-none-any.whl (72 kB)
Collecting Jinja2
  Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting binaryornot
  Using cached binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
Collecting boolean.py
  Using cached boolean.py-3.8-py2.py3-none-any.whl (23 kB)
Collecting license-expression
  Using cached license_expression-1.2-py2.py3-none-any.whl (20 kB)
Collecting chardet>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp38-cp38-win_amd64.whl (16 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\miniforge3\envs\python\lib\site-packages (from requests->reuse) (2020.12.5)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
Installing collected packages: urllib3, six, MarkupSafe, idna, chardet, boolean.py, requests, python-debian, license-expression, Jinja2, binaryornot, reuse
Successfully installed Jinja2-2.11.3 MarkupSafe-1.1.1 binaryornot-0.4.4 boolean.py-3.8 chardet-4.0.0 idna-2.10 license-expression-1.2 python-debian-0.1.39 requests-2.25.1 reuse-0.12.1 six-1.15.0 urllib3-1.26.3
```
### Possible Root Cause

This import causes the problem:
```
File "c:\programdata\miniforge3\envs\python\lib\site-packages\reuse\_util.py", line 26, in <module>
    from debian.copyright import Copyright
```

It seems that `python-debian`version 0.1.39 introduced the problem. Uninstalling it manually and installing 0.1.38 solved the problem.

**Comment by schlauch** [comment]
It seems to be already fixed in the master pf python-debian: https://salsa.debian.org/python-debian-team/python-debian/-/blob/b3e0d0f3b77e5107a5b627faf0c459bd3b47b1f1/lib/debian/changelog.py#L102

**Comment by mxmehl** [comment]
I assume this has been fixed with an update? If not, please feel free to reopen :)

**Comment by schlauch** [comment]
I think it will be resolved with the next python-debian version. So far 0.1.39 is still the latest version.

**Comment by marcoXbresciani** [comment]
Only a mention to the installation procedure for python-debian "previous version".
I'm absolutely ignorant of Python, add to search for it: I hope this note will help other users: I've moved back from python-debian 0.1.39 (already installed) to 0.1.38 using `pip3 install -Iv --user python-debian==0.1.38` on Windows 10 Enterprise, Command Prompt with Python 3.9.5.
