### ISSUE TITLE
REUSE under Windows

### ISSUE THREAD

**Issue by BLumia** [fsfe/reuse-tool#555]
While trying to use REUSE tool to check my project, I saw it complains `ModuleNotFoundError: No module named 'pwd'` when running `reuse lint` under my Windows 11 installation (logs below). Or should I open another issue for the Windows supporting question?

`$env:PYTHONUTF8="1"` was set or it will complain `UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 105444: illegal multibyte sequence` when running under a non UTF-8 Windows installation (Simplified Chinese for example). The following are the errors while trying to run `reuse lint`:

```
Traceback (most recent call last):
  File "C:\Users\Gary\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Gary\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Gary\AppData\Roaming\Python\Python38\Scripts\reuse.exe\__main__.py", line 4, in <module>
  File "C:\Users\Gary\AppData\Roaming\Python\Python38\site-packages\reuse\_main.py", line 15, in <module>
    from . import (
  File "C:\Users\Gary\AppData\Roaming\Python\Python38\site-packages\reuse\download.py", line 18, in <module>
    from ._util import (
  File "C:\Users\Gary\AppData\Roaming\Python\Python38\site-packages\reuse\_util.py", line 28, in <module>
    from debian.copyright import Copyright
  File "C:\Users\Gary\AppData\Roaming\Python\Python38\site-packages\debian\copyright.py", line 59, in <module>
    from debian import deb822
  File "C:\Users\Gary\AppData\Roaming\Python\Python38\site-packages\debian\deb822.py", line 321, in <module>
    import debian.changelog
  File "C:\Users\Gary\AppData\Roaming\Python\Python38\site-packages\debian\changelog.py", line 93, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'
```

**Comment by carmenbianca** [comment]
Related to #466. python-debian is an unfortunate dependency and will be replaced at some point. You can try to install an older version of python-debian. 0.1.38 should work.

Windows support is not really a priority though.

**Comment by BLumia** [comment]
> Windows support is not really a priority though.

I understand. I mainly work under Linux desktop distribution but also use Windows in some case, so it could be better if it also works under Windows :)

**Comment by stephanlachnit** [comment]
Is this still an issue?

python-debian now runs their test on Windows in their CI (via wine): https://salsa.debian.org/python-debian-team/python-debian/-/pipelines/457575

**Comment by BLumia** [comment]
Seems working now, tested with version 1.1.1. Thanks for the info :)
