### ISSUE TITLE
reuse annotate fails on year range

### ISSUE THREAD

**Issue by jzarl** [fsfe/reuse-tool#647]
If the copyright year is given as a "YYYY-YYYY" range (without spaces), reuse annotate/addheader fails with the following traceback:

    Traceback (most recent call last):
      File "/usr/bin/reuse", line 8, in <module>
        sys.exit(main())
                 ^^^^^^
      File "/usr/lib/python3/dist-packages/reuse/_main.py", line 283, in main
        return parsed_args.func(parsed_args, project, out)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/reuse/header.py", line 788, in run
        result += _add_header_to_file(
                  ^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/reuse/header.py", line 507, in _add_header_to_file
        output = find_and_replace_header(
                 ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/reuse/header.py", line 306, in find_and_replace_header
        header = create_header(
                 ^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/reuse/header.py", line 167, in create_header
        spdx_copyrights = merge_copyright_lines(
                          ^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/reuse/_util.py", line 239, in merge_copyright_lines
        "year": _parse_copyright_year(
                ^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/reuse/_util.py", line 219, in _parse_copyright_year
        if re.match(r"\d{4}$", year):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/re/__init__.py", line 166, in match
        return _compile(pattern, flags).match(string)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: expected string or bytes-like object, got 'NoneType'

I checked with https://spdx.github.io/spdx-spec/v2.3/file-tags/#h2-file-tags-format and it seems that date ranges without spaces surrounding the "-" character are permitted by the standard.

## Steps to reproduce

    # mkdir check-reuse-daterange ; cd check-reuse-daterange
    # git init
    # printf '\n' > file.md ; cat file.md 
    
    # reuse annotate --merge-copyrights --copyright "John Doe <john@example.com>" --year 2023 file.md 2>&1 ; cat file.md 
    Traceback (most recent call last):
      File "/usr/bin/reuse", line 8, in <module>
        sys.exit(main())
                 ^^^^^^
      File "/usr/lib/python3/dist-packages/reuse/_main.py", line 283, in main
        return parsed_args.func(parsed_args, project, out)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/reuse/header.py", line 788, in run
        result += _add_header_to_file(
                  ^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/reuse/header.py", line 507, in _add_header_to_file
        output = find_and_replace_header(
                 ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/reuse/header.py", line 306, in find_and_replace_header
        header = create_header(
                 ^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/reuse/header.py", line 167, in create_header
        spdx_copyrights = merge_copyright_lines(
                          ^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/reuse/_util.py", line 239, in merge_copyright_lines
        "year": _parse_copyright_year(
                ^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/reuse/_util.py", line 219, in _parse_copyright_year
        if re.match(r"\d{4}$", year):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/re/__init__.py", line 166, in match
        return _compile(pattern, flags).match(string)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: expected string or bytes-like object, got 'NoneType'

**Comment by nicorikken** [comment]
Thanks for reporting this and proposing a pull-request. I think the stacktrace should be prevented.

I'm not sure how accepting reuse-tool should be for date-ranges. The answer to that question dictates the way to fix it.

**Comment by jzarl** [comment]
@nicorikken 
As for how accepting reuse-tool should be for date-ranges: at the minimum, the examples cited in the SPDX specification should be accepted. Since reuse-tool already uses the format containing spaces around the dash, this probably should be accepted as well.

In the pull request I went for Postel's law and tried to be liberal in what is accepted (since it will be normalized by reuse-tool), but I'm not overly invested in one way or another...
