### ISSUE TITLE
ImportError: cannot import name 'PathLike'

### ISSUE THREAD

**Issue by warpr** [fsfe/reuse-tool#93]
Hello,

I was trying to run reuse, but ran into an ImportError.  Any idea why reuse cannot find its imports?

```
09:56 kuno@pink-yoshi:~/code$ mkdir reuse
09:56 kuno@pink-yoshi:~/code$ cd reuse
09:56 kuno@pink-yoshi:~/code/reuse$ python3 -m venv ve
09:57 kuno@pink-yoshi:~/code/reuse$ ve/bin/pip install fsfe-reuse
Collecting fsfe-reuse
  Using cached https://files.pythonhosted.org/packages/30/11/f96ce5e81048ac1af34f68725c22ec88131c137ffa22ddf7814af917ce5c/fsfe_reuse-0.5.0-py3-none-any.whl
Collecting python-debian (from fsfe-reuse)
  Using cached https://files.pythonhosted.org/packages/87/49/a34a602141db50b101a25d1f256b33cfb7b406bafd0f00e071a5f7424c92/python_debian-0.1.36-py3-none-any.whl
Collecting license-expression (from fsfe-reuse)
  Using cached https://files.pythonhosted.org/packages/de/6b/65b4a2ee355a1ea1b78bdc858e314e767cedcc44e8aaf9cd46e4da41674b/license_expression-0.999-py2.py3-none-any.whl
Collecting binaryornot (from fsfe-reuse)
  Using cached https://files.pythonhosted.org/packages/24/7e/f7b6f453e6481d1e233540262ccbfcf89adcd43606f44a028d7f5fae5eb2/binaryornot-0.4.4-py2.py3-none-any.whl
Collecting boolean.py (from fsfe-reuse)
  Using cached https://files.pythonhosted.org/packages/9b/27/d22062a221010e17935237ba4b574cd828238ea02e0765337c238466a512/boolean.py-3.6-py2.py3-none-any.whl
Collecting Jinja2 (from fsfe-reuse)
  Using cached https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl
Collecting requests (from fsfe-reuse)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting six (from python-debian->fsfe-reuse)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting chardet (from python-debian->fsfe-reuse)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2->fsfe-reuse)
  Using cached https://www.piwheels.org/simple/markupsafe/MarkupSafe-1.1.1-cp35-cp35m-linux_armv7l.whl
Collecting idna<2.9,>=2.5 (from requests->fsfe-reuse)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->fsfe-reuse)
  Using cached https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->fsfe-reuse)
  Using cached https://files.pythonhosted.org/packages/81/b7/cef47224900ca67078ed6e2db51342796007433ad38329558f56a15255f5/urllib3-1.25.5-py2.py3-none-any.whl
Installing collected packages: six, chardet, python-debian, boolean.py, license-expression, binaryornot, MarkupSafe, Jinja2, idna, certifi, urllib3, requests, fsfe-reuse
Successfully installed Jinja2-2.10.1 MarkupSafe-1.1.1 binaryornot-0.4.4 boolean.py-3.6 certifi-2019.9.11 chardet-3.0.4 fsfe-reuse-0.5.0 idna-2.8 license-expression-0.999 python-debian-0.1.36 requests-2.22.0 six-1.12.0 urllib3-1.25.5
09:56 kuno@pink-yoshi:~/code/reuse$ cd ..
09:59 kuno@pink-yoshi:~/code$ cd reuse-example/
09:59 kuno@pink-yoshi:~/code/reuse-example (master)$ ../reuse/ve/bin/reuse lint
Traceback (most recent call last):
  File "../reuse/ve/bin/reuse", line 7, in <module>
    from reuse._main import main
  File "/home/kuno/code/reuse/ve/lib/python3.5/site-packages/reuse/_main.py", line 13, in <module>
    from . import (
  File "/home/kuno/code/reuse/ve/lib/python3.5/site-packages/reuse/download.py", line 11, in <module>
    from os import PathLike
ImportError: cannot import name 'PathLike'
09:59 kuno@pink-yoshi:~/code/reuse-example (master)$
```

System:
```
09:59 kuno@pink-yoshi:~/code/reuse-example (master)$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch
```

**Comment by warpr** [comment]
Oh nevermind, I just noticed in the README that it requires python 3.6, and my system python 3 is older.
